// Sample product data
const products = [
  {
    id: 1,
    title: "Wireless Bluetooth Headphones",
    price: 59.99,
    image: "/api/placeholder/300/200",
    category: "electronics",
    rating: 4.5,
  },
  {
    id: 2,
    title: "Men's Casual T-Shirt",
    price: 24.99,
    image: "/api/placeholder/300/200",
    category: "clothing",
    rating: 4.2,
  },
  {
    id: 3,
    title: "Smart Watch",
    price: 129.99,
    image: "/api/placeholder/300/200",
    category: "electronics",
    rating: 4.8,
  },
  {
    id: 4,
    title: "Non-Stick Cookware Set",
    price: 89.99,
    image: "/api/placeholder/300/200",
    category: "home",
    rating: 4.3,
  },
  {
    id: 5,
    title: "Skincare Gift Set",
    price: 49.99,
    image: "/api/placeholder/300/200",
    category: "beauty",
    rating: 4.7,
  },
  {
    id: 6,
    title: "Women's Running Shoes",
    price: 79.99,
    image: "/api/placeholder/300/200",
    category: "clothing",
    rating: 4.6,
  },
  {
    id: 7,
    title: "Smart Home Speaker",
    price: 119.99,
    image: "/api/placeholder/300/200",
    category: "electronics",
    rating: 4.4,
  },
  {
    id: 8,
    title: "Bedding Set - Queen",
    price: 69.99,
    image: "/api/placeholder/300/200",
    category: "home",
    rating: 4.1,
  },
  {
    id: 9,
    title: "Professional Hair Dryer",
    price: 89.99,
    image: "/api/placeholder/300/200",
    category: "beauty",
    rating: 4.6,
  },
  {
    id: 10,
    title: "Gaming Mechanical Keyboard",
    price: 129.99,
    image: "/api/placeholder/300/200",
    category: "electronics",
    rating: 4.8,
  },
  {
    id: 11,
    title: "Yoga Mat Premium",
    price: 35.99,
    image: "/api/placeholder/300/200",
    category: "fitness",
    rating: 4.7,
  },
  {
    id: 12,
    title: "Designer Sunglasses",
    price: 159.99,
    image: "/api/placeholder/300/200",
    category: "clothing",
    rating: 4.4,
  },
  {
    id: 13,
    title: "Smart Coffee Maker",
    price: 199.99,
    image: "/api/placeholder/300/200",
    category: "home",
    rating: 4.5,
  },
  {
    id: 14,
    title: "Organic Face Cream",
    price: 45.99,
    image: "/api/placeholder/300/200",
    category: "beauty",
    rating: 4.3,
  },
  {
    id: 15,
    title: "Wireless Gaming Mouse",
    price: 79.99,
    image: "/api/placeholder/300/200",
    category: "electronics",
    rating: 4.9,
  },
  {
    id: 16,
    title: "Premium Leather Wallet",
    price: 49.99,
    image: "/api/placeholder/300/200",
    category: "clothing",
    rating: 4.6,
  },
  {
    id: 17,
    title: "Air Purifier",
    price: 189.99,
    image: "/api/placeholder/300/200",
    category: "home",
    rating: 4.7,
  },
  {
    id: 18,
    title: "Vitamin C Serum",
    price: 29.99,
    image: "/api/placeholder/300/200",
    category: "beauty",
    rating: 4.5,
  },
];

module.exports = products;
